#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2014, Joyent, Inc.
#

#
# Run the SAPI tests.
# Run `./runtests -h` for usage info.
#

if [ "$TRACE" != "" ]; then
    export PS4='${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
    set -o xtrace
fi
set -o errexit
set -o pipefail



#---- guard

if [[ ! -f "/lib/sdc/.sdc-test-no-production-data" ]]; then
    cat <<EOF
To run this test you must create the file:

    /lib/sdc/.sdc-test-no-production-data

after ensuring you have no production data on this SDC.

Also, make sure that the sapi and imgapi zones have external nics.  See the
README for more detail.
EOF
    exit 2
fi



#---- config

NAME=sapi
TOP=$(cd $(dirname $0)/../; pwd)
NODE_INSTALL=${TOP}/build/node

export PATH=${NODE_INSTALL}/bin:$PATH


#---- support functions

function fatal
{
    echo "$(basename $0): fatal error: $*"
    exit 1
}

function usage
{
    echo "Usage:"
    echo "  runtests [OPTIONS...]"
    echo ""
    echo "Options:"
    echo "  -f FILTER   Filter pattern (substring match) for test files to run."
}



#---- mainline

start_time=$(date +%s)

# Options.
opt_test_pattern='*'
while getopts "hf:" opt
do
    case "$opt" in
        h)
            usage
            exit 0
            ;;
        f)
            opt_test_pattern="*${OPTARG}*"
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

OUTPUT_DIR=/var/tmp/${NAME}test
echo "# Create output dir ($OUTPUT_DIR)."
rm -rf $OUTPUT_DIR
mkdir -p $OUTPUT_DIR



#---- start tests

svcadm disable -s sapi

cd ${TOP}
TEST_SAPI_PROTO_MODE=true ./node_modules/.bin/nodeunit \
    ./test/${opt_test_pattern}.test.js --reporter tap \
    | tee ${OUTPUT_DIR}/proto.tap
TEST_SAPI_PROTO_MODE=false ./node_modules/.bin/nodeunit \
    ./test/${opt_test_pattern}.test.js --reporter tap \
    | tee ${OUTPUT_DIR}/full.tap

svcadm enable -s sapi


#---- summary

echo ""
echo "# test results:"

end_time=$(date +%s)
elapsed=$((${end_time} - ${start_time}))
echo "# Completed in ${elapsed} seconds."
