#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2018, Joyent, Inc.
#

#
# Rsync the master in this working copy to the install on the given HN.
#

#set -o xtrace
set -o errexit

TOP=$(cd $(dirname $0)/../; pwd)
NODE=root@$1

if [[ -z "$SAPI_ZONE" ]]; then
    SAPI_ZONE=$(ssh $NODE vmadm lookup -1 alias=sapi0 state=running)
fi
echo "SAPI_ZONE: $SAPI_ZONE"

extraOpts=
if [[ $(uname -s) != "SunOS" ]]; then
    extraOpts="--exclude *.node --exclude build"
else
    # Clean node_modules everytime.
    ssh $NODE rm -rf /zones/$SAPI_ZONE/root/opt/smartdc/sapi/node_modules
fi

rsync -av ${TOP}/ \
    $NODE:/zones/$SAPI_ZONE/root/opt/smartdc/sapi/ \
    $extraOpts \
    --exclude .git/ \
    --exclude /bin/ \
    --exclude /boot/ \
    --exclude /build/ \
    --exclude /cmd/ \
    --exclude /deps/ \
    --exclude /docs/ \
    --exclude /etc/ \
    --exclude /tmp/

state=$(ssh ${NODE} svcs -z ${SAPI_ZONE} -H -o state sapi)
if [[ "$state" == "maintenance" ]]; then
    ssh ${NODE} svcadm -z ${SAPI_ZONE} clear sapi
else
    ssh ${NODE} svcadm -z ${SAPI_ZONE} restart sapi
fi
ssh ${NODE} svcadm -z ${SAPI_ZONE} restart config-agent
